### ISSUE TITLE
Table id for reporting

### ISSUE THREAD

**Issue by avstaylime** [bemeir/magento2-rotate-encryption-keys#2]
The script is looking for a table id in each table. The problem is the very last field _id is taken whereas the increment field is usually the very first field.

Replaced

```
if (preg_match('%_id$%', $fieldName)) {
                        $idField = $fieldName;
                        $idValue = $value;
                    }
```
with

```
if (preg_match('%_id$%', $fieldName)) {
                        $idField = $fieldName;
                        $idValue = $value;
                        break;
                    }
```

**Comment by vitaliy-golomoziy** [comment]
Good point, @avstaylime. Even better way is to use table's description, as there is no guarantee that the first field is necessary an id.

**Comment by vitaliy-golomoziy** [comment]
This should be fixed once https://github.com/bemeir/magento2-rotate-encryption-keys/pull/7 gets merged. We used primary key obtained from a table's description.
