### ISSUE TITLE
update-record option doesn't work

### ISSUE THREAD

**Issue by quyendam2612** [bemeir/magento2-rotate-encryption-keys#5]
https://github.com/bemeir/magento2-rotate-encryption-keys/blob/ecdd174b7153934c4938fc22f329c4580f4a5c28/update-encryption.php#L170

Why exiting when using `update-record` option with `id` is set?
I think with available ID and when `update-record` option is being used, we should proceed instead of ending the script?

Correct me if I am wrong.

**Comment by vitaliy-golomoziy** [comment]
Yes, that is correct! 
This will be fixed in the new version, see: https://github.com/bemeir/magento2-rotate-encryption-keys/pull/7
